name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build Default
      run: cargo build --verbose
    - name: Test Default
      run: cargo test --verbose
    - name: Build Full
      run: cargo build --verbose --features extra-data
    - name: Test Full
      run: cargo test --verbose --features extra-data
